"""initial schema

Revision ID: f42338a06001
Revises: 
Create Date: 2026-05-13 06:06:18.750905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42338a06001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('booklet_pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('booklet_type', sa.String(), server_default='standard', nullable=False),
    sa.Column('intro_page', sa.Integer(), server_default='2', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_models_owner_user_id'), 'answer_models', ['owner_user_id'], unique=False)
    op.create_table('key_uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('booklet_type', sa.String(), server_default='standard', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_uploads_owner_user_id'), 'key_uploads', ['owner_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_key_uploads_owner_user_id'), table_name='key_uploads')
    op.drop_table('key_uploads')
    op.drop_index(op.f('ix_answer_models_owner_user_id'), table_name='answer_models')
    op.drop_table('answer_models')
    # ### end Alembic commands ###
